spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///fresh_shop?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 8090
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



